# Generated by Django 4.0.1 on 2022-01-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmpId', models.AutoField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('DOJ', models.DateField()),
                ('Avatar', models.CharField(max_length=150)),
            ],
        ),
    ]
