# Generated by Django 4.0.1 on 2022-01-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='DepartmentName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
